// const companyFieldMapping = {
//     "CompanyName": "Company Name",
//     "Company Name": "Company Name",
//     "CompaniesName": "Company Name",
//     "Companies Name": "Company Name",
//     "Company": "Company Name",
//     "Companies": "Company Name",
//     "Name": "Company Name",
//     "OrganisationName": "Company Name",
//     "Organisation Name": "Company Name",
//     "OrganizationName": "Company Name",
//     "Organization Name": "Company Name",
//     "Organization": "Company Name",
//     "AccountName": "Company Name",
//     "Account Name": "Company Name",
//     "Account": "Company Name",
//     "Accounts": "Company Name",

//     "Countries": "Country",

//     "MainlineNumber": "Main Line Number",
//     "Mainline Number": "Main Line Number",
//     "Main Line": "Main Line Number",
//     "Number": "Main Line Number",
//     "Phone": "Main Line Number",
//     "Phone No.": "Main Line Number",
//     "Phone No": "Main Line Number",
//     "Phone #": "Main Line Number",
//     "Phone#": "Main Line Number",

//     "Company email": "Company Email",
//     "Organisationemail": "Company Email",
//     "Organisation email": "Company Email",
//     "Organizationemail": "Company Email",
//     "Organization email": "Company Email",
//     "Corporateemail": "Company Email",
//     "Corporate Email": "Company Email",
//     "Email": "Company Email",

//     "Address ": "Address",
//     "Addresses": "Address",
//     "Officeaddress": "Address",
//     "Office address": "Address",
//     "Companyaddress": "Address",
//     "Company Address": "Address",
//     "Companiesaddress": "Address",
//     "Companies Address": "Address",
//     "OrganisationAddress": "Address",
//     "Organization Address": "Address",
//     "OrganisationAddress": "Address",
//     "Organisation Address": "Address",

//     "Website": "Website Link",
//     "WebsiteLink": "Website Link",
//     "Website ": "Website Link",
//     "Website Links": "Website Link",
//     "WebsiteLink": "Website Link",
//     "URL": "Website Link",
//     "URL Link": "Website Link",
//     "URLLink": "Website Link",
//     "URL Links": "Website Link",
//     "URLLinks": "Website Link",
//     "CompanyWebsite": "Website Link",
//     "OrganizationWebsite": "Website Link",
//     "OrganisatioWebsite": "Website Link",

//     "FacebookLink": "Facebook Link",
//     "Facebook": "Facebook Link",
//     "FB": "Facebook Link",
//     "FacebookLikes": "Facebook Likes",
//     "Likes": "Facebook Likes",

//     "InstagramLink": "Instagram Link",
//     "Instagram": "Instagram Link",

//     "Instagram Post": "Instagram Posts",
//     "InstagramPost": "Instagram Posts",
//     "InstagramPosts": "Instagram Posts",
//     "IG Post": "Instagram Posts",
//     "IGPost": "Instagram Posts",
//     "IG Posts": "Instagram Posts",
//     "IGPosts": "Instagram Posts",
//     "IG": "Instagram Posts",

//     "InstagramFollowers": "Instagram Followers",
//     "Instagram Follower": "Instagram Followers",
//     "InstagramFollower": "Instagram Followers",
//     "IG Followers": "Instagram Followers",
//     "IGFollowers": "Instagram Followers",
//     "IG Follower": "Instagram Followers",
//     "IGFollower": "Instagram Followers",

//     "Twitterlink": "Twitter Link",
//     "Twitter": "Twitter Link",
//     "Twitter Links": "Twitter Link",
//     "TwitterLinks": "Twitter Link",

//     "TwitterFollowers": "Twitter Followers",
//     "Twitter Follower": "Twitter Followers",
//     "TwitterFollower": "Twitter Followers",
//     "TWTR Followers": "Twitter Followers",
//     "TWTRFollowers": "Twitter Followers",
//     "TWTR Follower": "Twitter Followers",
//     "TWTRFollower": "Twitter Followers",

//     "YoutubeLink": "Youtube Link",
//     "Youtube Links": "Youtube Link",
//     "YoutubeLinks": "Youtube Link",
//     "Youtube": "Youtube Link",
//     "YT ": "Youtube Link",
//     "YT Link": "Youtube Link",
//     "YTLink": "Youtube Link",
//     "YT Links": "Youtube Link",
//     "YTLinks": "Youtube Link",

//     "YoutubeSubscribers": "Youtube Subscribers",
//     "Youtube Subscriber": "Youtube Subscribers",
//     "YoutubeSubscriber": "Youtube Subscribers",
//     "YT Subscribers": "Youtube Subscribers",
//     "YTSubscribers": "Youtube Subscribers",
//     "YT Subscriber": "Youtube Subscribers",
//     "YTSubscriber": "Youtube Subscribers",

//     "LinkedinLink": "Linkedin Link",
//     "Linkedin Links": "Linkedin Link",
//     "LinkedinLinks": "Linkedin Link",
//     "Linkedin": "Linkedin Link",
//     "LI Link": "Linkedin Link",
//     "LILink": "Linkedin Link",
//     "LI Links": "Linkedin Link",
//     "LILinks": "Linkedin Link",

//     "LinkedinFollowers": "Linkedin Followers",
//     "Linkedin Follower": "Linkedin Followers",
//     "LinkedinFollower": "Linkedin Followers",
//     "LI followers": "Linkedin Followers",
//     "Lifollowers": "Linkedin Followers",
//     "LI Follower": "Linkedin Followers",
//     "Lifollower": "Linkedin Followers",

//     "Titles": "Title",

//     "Descriptions": "Description",
//     "Des": "Description",
//     "Descript": "Description",

//     "Year in Opetation": "Years in Operation",
//     "Year": "Years in Operation",
//     "Years": "Years in Operation",
//     "Company Age": "Years in Operation",
//     "CompanyAge": "Years in Operation",
//     "Age": "Years in Operation",
//     "Year Founded": "Years in Operation",
//     "YearFounded": "Years in Operation",

//     "EmployeeSize": "Employee Size",
//     "Employees Size": "Employee Size",
//     "EmployeesSize": "Employee Size",
//     "Size": "Employee Size",
//     "Employee": "Employee Size",
//     "Employees": "Employee Size",
//     "Company Size": "Employee Size",
//     "CompanySize": "Employee Size",
//     "Staff": "Employee Size",
//     "Number of Staff": "Employee Size",
//     "Numberofstaff": "Employee Size",
//     "No of Staff": "Employee Size",

//     "HQLocation": "HQ Location",
//     "HQ Locations": "HQ Location",
//     "HQLocations": "HQ Location",
//     "HQ": "HQ Location",
//     "Head Quarter": "HQ Location",
//     "Headquater": "HQ Location",
//     "Company HQ": "HQ Location",
//     "CompanyHQ": "HQ Location",
//     "Organization HQ": "HQ Location",
//     "OrganizationHQ": "HQ Location",
//     "Organisation HQ": "HQ Location",
//     "OrganisationHQ": "HQ Location",
//     "Account HQ": "HQ Location",
//     "AccountHQ": "HQ Location",

//     "CountryPresence": "Country Presence",
//     "Cty Presence": "Country Presence",
//     "CtyPresence": "Country Presence",
//     "Country Location": "Country Presence",
//     "CountryLocation": "Country Presence",
//     "Country Locations": "Country Presence",
//     "CountryLocations": "Country Presence",
//     "Office Location": "Country Presence",
//     "Officelocation": "Country Presence",
//     "Office Locations": "Country Presence",
//     "OfficeLocations": "Country Presence",

//     "CityPresence": "City Presence",
//     "City Location": "City Presence",
//     "CityLocation": "City Presence",
//     "City Locations": "City Presence",
//     "CityLocations": "City Presence",

//     "Business Type (Des/title)": "Business Type ( Des/Title )",
//     "Business Type(Des/title)": "Business Type ( Des/Title )",
//     "Businesstype(Des/title)": "Business Type ( Des/Title )",
//     "Businesstype (Des/title)": "Business Type ( Des/Title )",
//     "Business Type": "Business Type ( Des/Title )",
//     "BusinessType": "Business Type ( Des/Title )",
//     "Biz Type": "Business Type ( Des/Title )",
//     "Biztype": "Business Type ( Des/Title )",
//     "Organisation Type": "Business Type ( Des/Title )",
//     "OrganisationType": "Business Type ( Des/Title )",
//     "Organization Type": "Business Type ( Des/Title )",
//     "OrganizationType": "Business Type ( Des/Title )",

//     "Business Type (Website)": "Business Type ( Website )",
//     "Business Type(Website)": "Business Type ( Website )",
//     "BusinessType(Website)": "Business Type ( Website )",

//     "Start up": "Startup",
//     "Startups": "Startup",

//     "ChamberandAssoication": "Chamber and Association",
//     "Chambers and Asosications": "Chamber and Association",
//     "Chamber": "Chamber and Association",
//     "Chmabers": "Chamber and Association",
//     "Association": "Chamber and Association",
//     "Associations": "Chamber and Association",

//     "Manufacturers": "Manufacturer",
//     "Producer": "Manufacturer",
//     "Producers": "Manufacturer",

//     "Wholesalers": "Wholesaler",

//     "DistributornReseller": "Distributor n Reseller",
//     "Distributors n Resellers": "Distributor n Reseller",
//     "DistributorsnResellers": "Distributor n Reseller",
//     "Distributor": "Distributor n Reseller",
//     "Distributors": "Distributor n Reseller",
//     "Reseller": "Distributor n Reseller",
//     "Resellers": "Distributor n Reseller",

//     "Exporters": "Exporter",
//     "Export": "Exporter",

//     "ServicceProvider": "Service Provider",
//     "Service Providers": "Service Provider",
//     "ServiceProviders": "Service Provider",

//     "Retailers": "Retailer",

//     "SalesChannel": "Sales Channel",
//     "Sales Channels": "Sales Channel",
//     "SalesChannels": "Sales Channel",

//     "PhysicalStore": "Physical Store",
//     "Physical Stores": "Physical Store",
//     "PhysicalStores": "Physical Store",
//     "Stores": "Physical Store",

//     "OnlineStore": "Online Store",
//     "Online Stores": "Online Store",
//     "OnlineStores": "Online Store",
//     "Online": "Online Store",

//     "Market Place": "Marketplace",
//     "Marketplaces": "Marketplace",

// }

const companyFieldMapping = {
  COMPANYNAME: "Company Name",
  "COMPANY NAME": "Company Name",
  COMPANIESNAME: "Company Name",
  "COMPANIES NAME": "Company Name",
  COMPANY: "Company Name",
  COMPANIES: "Company Name",
  NAME: "Company Name",
  ORGANISATIONNAME: "Company Name",
  "ORGANISATION NAME": "Company Name",
  ORGANIZATIONNAME: "Company Name",
  "ORGANIZATION NAME": "Company Name",
  ORGANIZATION: "Company Name",
  ACCOUNTNAME: "Company Name",
  "ACCOUNT NAME": "Company Name",
  ACCOUNT: "Company Name",
  ACCOUNTS: "Company Name",
  COUNTRIES: "Country",
  MAINLINENUMBER: "Main Line Number",
  "MAINLINE NUMBER": "Main Line Number",
  "MAIN LINE": "Main Line Number",
  NUMBER: "Main Line Number",
  PHONE: "Main Line Number",
  "PHONE NO.": "Main Line Number",
  "PHONE NO": "Main Line Number",
  "PHONE #": "Main Line Number",
  "PHONE#": "Main Line Number",
  "COMPANY EMAIL": "Company Email",
  ORGANISATIONEMAIL: "Company Email",
  "ORGANISATION EMAIL": "Company Email",
  ORGANIZATIONEMAIL: "Company Email",
  "ORGANIZATION EMAIL": "Company Email",
  CORPORATEEMAIL: "Company Email",
  "CORPORATE EMAIL": "Company Email",
  EMAIL: "Company Email",
  "ADDRESS ": "Address",
  ADDRESSES: "Address",
  OFFICEADDRESS: "Address",
  "OFFICE ADDRESS": "Address",
  COMPANYADDRESS: "Address",
  "COMPANY ADDRESS": "Address",
  COMPANIESADDRESS: "Address",
  "COMPANIES ADDRESS": "Address",
  ORGANISATIONADDRESS: "Address",
  "ORGANIZATION ADDRESS": "Address",
  "ORGANISATION ADDRESS": "Address",
  WEBSITE: "Website Link",
  WEBSITELINK: "Website Link",
  "WEBSITE ": "Website Link",
  "WEBSITE LINKS": "Website Link",
  URL: "Website Link",
  "URL LINK": "Website Link",
  URLLINK: "Website Link",
  "URL LINKS": "Website Link",
  URLLINKS: "Website Link",
  COMPANYWEBSITE: "Website Link",
  ORGANIZATIONWEBSITE: "Website Link",
  ORGANISATIOWEBSITE: "Website Link",
  FACEBOOKLINK: "Facebook Link",
  FACEBOOK: "Facebook Link",
  FB: "Facebook Link",
  FACEBOOKLIKES: "Facebook Likes",
  LIKES: "Facebook Likes",
  INSTAGRAMLINK: "Instagram Link",
  INSTAGRAM: "Instagram Link",
  "INSTAGRAM POST": "Instagram Posts",
  INSTAGRAMPOST: "Instagram Posts",
  INSTAGRAMPOSTS: "Instagram Posts",
  "IG POST": "Instagram Posts",
  IGPOST: "Instagram Posts",
  "IG POSTS": "Instagram Posts",
  IGPOSTS: "Instagram Posts",
  IG: "Instagram Posts",
  INSTAGRAMFOLLOWERS: "Instagram Followers",
  "INSTAGRAM FOLLOWER": "Instagram Followers",
  INSTAGRAMFOLLOWER: "Instagram Followers",
  "IG FOLLOWERS": "Instagram Followers",
  IGFOLLOWERS: "Instagram Followers",
  "IG FOLLOWER": "Instagram Followers",
  IGFOLLOWER: "Instagram Followers",
  TWITTERLINK: "Twitter Link",
  TWITTER: "Twitter Link",
  "TWITTER LINKS": "Twitter Link",
  TWITTERLINKS: "Twitter Link",
  TWITTERFOLLOWERS: "Twitter Followers",
  "TWITTER FOLLOWER": "Twitter Followers",
  TWITTERFOLLOWER: "Twitter Followers",
  "TWTR FOLLOWERS": "Twitter Followers",
  TWTRFOLLOWERS: "Twitter Followers",
  "TWTR FOLLOWER": "Twitter Followers",
  TWTRFOLLOWER: "Twitter Followers",
  YOUTUBELINK: "Youtube Link",
  "YOUTUBE LINKS": "Youtube Link",
  YOUTUBELINKS: "Youtube Link",
  YOUTUBE: "Youtube Link",
  "YT ": "Youtube Link",
  "YT LINK": "Youtube Link",
  YTLINK: "Youtube Link",
  "YT LINKS": "Youtube Link",
  YTLINKS: "Youtube Link",
  YOUTUBESUBSCRIBERS: "Youtube Subscribers",
  "YOUTUBE SUBSCRIBER": "Youtube Subscribers",
  YOUTUBESUBSCRIBER: "Youtube Subscribers",
  "YT SUBSCRIBERS": "Youtube Subscribers",
  YTSUBSCRIBERS: "Youtube Subscribers",
  "YT SUBSCRIBER": "Youtube Subscribers",
  YTSUBSCRIBER: "Youtube Subscribers",
  LINKEDINLINK: "Linkedin Link",
  "LINKEDIN LINKS": "Linkedin Link",
  LINKEDINLINKS: "Linkedin Link",
  LINKEDIN: "Linkedin Link",
  "LI LINK": "Linkedin Link",
  LILINK: "Linkedin Link",
  "LI LINKS": "Linkedin Link",
  LILINKS: "Linkedin Link",
  LINKEDINFOLLOWERS: "Linkedin Followers",
  "LINKEDIN FOLLOWER": "Linkedin Followers",
  LINKEDINFOLLOWER: "Linkedin Followers",
  "LI FOLLOWERS": "Linkedin Followers",
  LIFOLLOWERS: "Linkedin Followers",
  "LI FOLLOWER": "Linkedin Followers",
  LIFOLLOWER: "Linkedin Followers",
  TITLES: "Title",
  DESCRIPTIONS: "Description",
  DES: "Description",
  DESCRIPT: "Description",
  "YEAR IN OPETATION": "Years in Operation",
  YEAR: "Years in Operation",
  YEARS: "Years in Operation",
  "COMPANY AGE": "Years in Operation",
  COMPANYAGE: "Years in Operation",
  AGE: "Years in Operation",
  "YEAR FOUNDED": "Years in Operation",
  YEARFOUNDED: "Years in Operation",
  EMPLOYEESIZE: "Employee Size",
  "EMPLOYEES SIZE": "Employee Size",
  EMPLOYEESSIZE: "Employee Size",
  SIZE: "Employee Size",
  EMPLOYEE: "Employee Size",
  EMPLOYEES: "Employee Size",
  "COMPANY SIZE": "Employee Size",
  COMPANYSIZE: "Employee Size",
  STAFF: "Employee Size",
  "NUMBER OF STAFF": "Employee Size",
  NUMBEROFSTAFF: "Employee Size",
  "NO OF STAFF": "Employee Size",
  HQLOCATION: "HQ Location",
  "HQ LOCATIONS": "HQ Location",
  HQLOCATIONS: "HQ Location",
  HQ: "HQ Location",
  "HEAD QUARTER": "HQ Location",
  HEADQUATER: "HQ Location",
  "COMPANY HQ": "HQ Location",
  COMPANYHQ: "HQ Location",
  "ORGANIZATION HQ": "HQ Location",
  ORGANIZATIONHQ: "HQ Location",
  "ORGANISATION HQ": "HQ Location",
  ORGANISATIONHQ: "HQ Location",
  "ACCOUNT HQ": "HQ Location",
  ACCOUNTHQ: "HQ Location",
  COUNTRYPRESENCE: "Country Presence",
  "CTY PRESENCE": "Country Presence",
  CTYPRESENCE: "Country Presence",
  "COUNTRY LOCATION": "Country Presence",
  COUNTRYLOCATION: "Country Presence",
  "COUNTRY LOCATIONS": "Country Presence",
  COUNTRYLOCATIONS: "Country Presence",
  "OFFICE LOCATION": "Country Presence",
  OFFICELOCATION: "Country Presence",
  "OFFICE LOCATIONS": "Country Presence",
  OFFICELOCATIONS: "Country Presence",
  CITYPRESENCE: "City Presence",
  "CITY LOCATION": "City Presence",
  CITYLOCATION: "City Presence",
  "CITY LOCATIONS": "City Presence",
  CITYLOCATIONS: "City Presence",
  "BUSINESS TYPE (DES/TITLE)": "Business Type (Des/Title)",
  "Business Type(Desc/Title)": "Business Type (Des/Title)",
  "BUSINESS TYPE(DES/TITLE)": "Business Type (Des/Title)",
  "BUSINESSTYPE(DES/TITLE)": "Business Type (Des/Title)",
  "BUSINESSTYPE (DES/TITLE)": "Business Type (Des/Title)",
  "BUSINESS TYPE": "Business Type (Des/Title)",
  BUSINESSTYPE: "Business Type (Des/Title)",
  "BIZ TYPE": "Business Type (Des/Title)",
  BIZTYPE: "Business Type (Des/Title)",
  "ORGANISATION TYPE": "Business Type (Des/Title)",
  ORGANISATIONTYPE: "Business Type (Des/Title)",
  "ORGANIZATION TYPE": "Business Type (Des/Title)",
  ORGANIZATIONTYPE: "Business Type (Des/Title)",
  "BUSINESS TYPE ( DESC/TITLE )": "Business Type (Des/Title)",
  "START UP": "Startup",
  STARTUPS: "Startup",
  CHAMBERANDASSOICATION: "Chamber and Association",
  "CHAMBERS AND ASOSICATIONS": "Chamber and Association",
  CHAMBER: "Chamber and Association",
  CHMABERS: "Chamber and Association",
  ASSOCIATION: "Chamber and Association",
  ASSOCIATIONS: "Chamber and Association",
  MANUFACTURERS: "Manufacturer",
  PRODUCER: "Manufacturer",
  PRODUCERS: "Manufacturer",
  WHOLESALERS: "Wholesaler",
  DISTRIBUTORNRESELLER: "Distributor n Reseller",
  "DISTRIBUTORS N RESELLERS": "Distributor n Reseller",
  DISTRIBUTORSNRESELLERS: "Distributor n Reseller",
  DISTRIBUTOR: "Distributor n Reseller",
  DISTRIBUTORS: "Distributor n Reseller",
  RESELLER: "Distributor n Reseller",
  RESELLERS: "Distributor n Reseller",
  EXPORTERS: "Exporter",
  EXPORT: "Exporter",
  SERVICCEPROVIDER: "Service Provider",
  "SERVICE PROVIDERS": "Service Provider",
  SERVICEPROVIDERS: "Service Provider",
  RETAILERS: "Retailer",
  "CHAMBER / ASSIOCIATIONS": "Chamber / Associations",
  SALESCHANNEL: "Sales Channel",
  "SALES CHANNELS": "Sales Channel",
  SALESCHANNELS: "Sales Channel",
  PHYSICALSTORE: "Physical Store",
  "PHYSICAL STORES": "Physical Store",
  PHYSICALSTORES: "Physical Store",
  STORES: "Physical Store",
  ONLINESTORE: "Online Store",
  "ONLINE STORES": "Online Store",
  ONLINESTORES: "Online Store",
  ONLINE: "Online Store",
  "MARKET PLACE": "Marketplace",
  MARKETPLACES: "Marketplace",

  "COMPANY NAME": "Company Name",
  COUNTRY: "Country",
  "MAIN LINE NUMBER": "Main Line Number",
  "COMPANY EMAIL": "Company Email",
  ADDRESS: "Address",
  "WEBSITE LINK": "Website Link",
  "FACEBOOK LINK": "Facebook Link",
  "FACEBOOK LIKES": "Facebook Likes",
  "INSTAGRAM LINK": "Instagram Link",
  "INSTAGRAM POSTS": "Instagram Posts",
  "INSTAGRAM FOLLOWERS": "Instagram Followers",
  "TWITTER LINK": "Twitter Link",
  "TWITTER FOLLOWERS": "Twitter Followers",
  "YOUTUBE LINK": "Youtube Link",
  "YOUTUBE SUBSCRIBERS": "Youtube Subscribers",
  "LINKEDIN LINK": "Linkedin Link",
  "LINKEDIN FOLLOWERS": "Linkedin Followers",
  TITLE: "Title",
  DESCRIPTION: "Description",
  "YEARS IN OPERATION": "Years in Operation",
  "EMPLOYEE SIZE": "Employee Size",
  "HQ LOCATION": "HQ Location",
  "COUNTRY PRESENCE": "Country Presence",
  "CITY PRESENCE": "City Presence",
  "BUSINESS TYPE ( DES/TITLE )": "Business Type ( Des/Title )",
  "BUSINESS TYPE ( WEBSITE )": "Business Type ( Website )",
  STARTUP: "Startup",
  "CHAMBER AND ASSOCIATION": "Chamber and Association",
  MANUFACTURER: "Manufacturer",
  WHOLESALER: "Wholesaler",
  "DISTRIBUTOR N RESELLER": "Distributor n Reseller",
  EXPORTER: "Exporter",
  "SERVICE PROVIDER": "Service Provider",
  RETAILER: "Retailer",
  "SALES CHANNEL": "Sales Channel",
  "PHYSICAL STORE": "Physical Store",
  "ONLINE STORE": "Online Store",
  MARKETPLACE: "Marketplace",

  "DECIDED BUSINESS TYPE": "Decided Business Type",
  "B2B PRODUCT": "B2B Product",
  "B2C PRODUCT": "B2C Product",
  "B2B SERVICES": "B2B Services",
  "B2C SERVICES": "B2C Services",

  "DEDUCED SECTORS (DES/TITLE)": "Deduced Sectors (Des/Title)",
  "Deduced sectors(Desc/Title)": "Deduced Sectors (Des/Title)",
  " DEDUCED SECTORS(DESC/TITLE)": "Deduced Sectors (Des/Title)",
  "DEDUCED SECTORS(DESC/TITLE)": "Deduced Sectors (Des/Title)",
  "DEDUCED SECTOR (WEBSITE)": "Deduced Sector (Website)",
  "DEDUCED SECTOR(WEBSITE)": "Deduced Sector (Website)",
  "Deduced Sector(Website)": "Deduced Sector (Website)",
  "DECIDED SECTOR": "Decided Sector",
  "ADVERTSING AND MARKETING SERVICES": "Advertsing And Marketing Services",
  "ADVERTISING AND MARKETING SERVICES": "Advertsing And Marketing Services",
  "ART ENTERTAINMENT AND MEDIA": "Art Entertainment And Media",
  "ARTENTERTAINMENT AND MEDIA": "Art Entertainment And Media",
  "BEAUTY PRODUCTS COSMETICS AND PERFUME":
    "Beauty Products Cosmetics and Perfume",
  "BUILDING AND INDUSTRIAL SUPPLY": "Building and Industrial Supply",
  "CHEMICAL METAL MINERAL NATURAL RESOURCE":
    "Chemical Metal Mineral Natural Resource",
  "CHEMICALMETALMINERALSNATURAL RESOURCE":
    "Chemical Metal Mineral Natural Resource",
  "CHEMICALMETALMINERALSNATURAL RESOURCES":
    "Chemical Metal Mineral Natural Resource",
  "CLOTHES BAGS AND SHOES": "Clothes Bags and Shoes",
  "CONSTRUCTION (SERVICES AND EQUIPMENT)":
    "Construction (Services and Equipment)",
  "CONSTRUCTION(SERVICES AND EQUIPMENT)":
    "Construction (Services and Equipment)",
  "CONSUMER ELECTRONICS": "Consumer Electronics",
  "DELIVERY PACKING AND LOGISTIC": "Delivery Packing and Logistic",
  "EDUCATION AND TRAINING": "Education and Training",
  "ENGINEERING AND TECHNICAL SERVICES": "Engineering and Technical Services",
  "FINANCE AND INSURANCE": "Finance and Insurance",
  "FOOD AND BEVERAGES": "Food and Beverages",
  HEALTHCARE: "Healthcare",
  "HOME AND PERSONAL SERVICES": "Home and Personal Services",
  "HOUSEHOLD FURNISHING AND APPLIANCES": "Household Furnishing and Appliances",
  "HOUSEHOLD FURNISHING AND APPLIANCE": "Household Furnishing and Appliances",
  "ICT(HARDWARE SYSTEM AND SERVICES)": "ICT(Hardware System and Services)",
  "ICT(HARDWARESYSTEM AND SERVICES)": "ICT(Hardware System and Services)",
  "ICT (HARDWARESYSTEM AND SERVICES)": "ICT(Hardware System and Services)",
  "JEWELLRY WATCH AND ACCESSORIES": "Jewellry Watch and Accessories",
  "MINING AND QUARRYING": "Mining and Quarrying",
  "PROFESSIONAL SERVICES": "Professional Services",
  "PROPERTY AND REAL ESTATE": "Property and Real Estate",
  "SOFTWARE ECOMMERCE AND GAMMING": "Software Ecommerce and Gamming",
  "SOFTWARE ECOMMERCE AND GAMING": "Software Ecommerce and Gamming",
  "TRAVEL AND TOURISM": "Travel and Tourism",
  "WATER AND WASTE MANAGEMENT": "Water and Waste Management",
  "DESCRIPTION(INSTAGRAM)": "Description(Instragram)",
  "BUSINESS TYPE (DES/TITLE)": "Business Type",
  "BUSINESS TYPE (WEBSITE)": "Business Type",
  "Business Type (Website)": "Business Type",
  "BUSINESS TYPE(DESC/TITLE)": "Business Type",
  "DECIDED BUSINESS TYPE": "Business Type",
  "BUSINESS TYPE (WEBSITE)": "Business Type",
  "BUSINESS TYPE(WEBSITE)": "Business Type",
  "BUSINESSTYPE(WEBSITE)": "Business Type",
  "BUSINESS TYPE ( WEBSITE )": "Business Type",
  "Business Type(Website)": "Business Type",
};

const companyContact = [
  "Company Name",
  "Country",
  "Main Line Number",
  "Company Email",
  "Fax",
  "Address",
  "Website Link",
  "Facebook Link",
  "Facebook Likes",
  "Instagram Link",
  "Instagram Posts",
  "Instagram Followers",
  "Twitter Link",
  "Twitter Followers",
  "Youtube Link",
  "Youtube Subscribers",
  "Twitter Links",
  "Twitter Followers",
  "Linkedin Link",
  "Linkedin Followers",
  "LinkedIn",
  "whatsaap",
];

const companyInfo = [
  "Title",
  "Description",
  "Description(Facebook)",
  "Description(Instragram)",
  "Description(Instagram)",
  "Description(LinkedIn)",
  "Description(Youtube)",
  "Description(Twitter)",
  "Years in Operation",
  "Employee Size",
  "HQ Location",
  "Country Presence",
  "City Presence",
  "Business Type",
  // "Startup",
  // "Chamber and Association",
  // "Manufacturer",
  // "Wholesaler",
  // "Distributor n Reseller",
  // "Exporter",
  // "Service Provider",
  // "Retailer",
  // "Sales Channel",
  // "Physical Store",
  // "Online Store",
  // "Marketplace",
  // "B2B Product",
  // "B2C Product",
];

const sector = [
  "Deduced Sectors (Des/Title)",
  "Deduced Sector (Website)",
  "Decided Sector",
  "Advertsing And Marketing Services",
  "Art Entertainment And Media",
  "Beauty Products Cosmetics and Perfume",
  "Building and Industrial Supply",
  "Chemical Metal Mineral Natural Resource",
  "Clothes Bags and Shoes",
  "Construction (Services and Equipment)",
  "Consumer Electronics",
  "Delivery Packing and Logistic",
  "Education and Training",
  "Engineering and Technical Services",
  "Finance and Insurance",
  "Food and Beverages",
  "Healthcare",
  "Home and Personal Services",
  "Household Furnishing and Appliances",
  "ICT(Hardware System and Services)",
  "Jewellry Watch and Accessories",
  "Mining and Quarrying",
  "Professional Services",
  "Property and Real Estate",
  "Software Ecommerce and Gamming",
  "Travel and Tourism",
  "Water and Waste Management",
];

const biz_type = [
  "Startup",
  "Chamber / Associations",
  "Directory",
  "Manufacturer",
  "Wholesaler",
  "Distributor / Reseller",
  "Exporter",
  "Service Provider",
  "Retailer",
];

const tableColumnMap = {
  // need to add more according to thier data
  "Company Name": "company_name",
  Country: "dataset",
  "Main Line Number": "main_line_number",
  Address: "address",
  "Website Link": "website",
  "Company Email": "company_email_address",
  "Facebook Link": "facebook",
  "Instagram Link": "instagram",
  "Twitter Link": "twitter",
  "Youtube Link": "youtube",
  "Linkedin Link": "linkedIn",
  "HQ Location": "main_hq_location",
  "Years in Operation": "year_in_operation",
  Description: "description",
  "Employee Size": "total_personnel",

  "Facebook Likes": "facebook_like",
  "Instagram Posts": "instagram_post",
  "Instagram Followers": "instagram_follower",
  "Twitter Followers": "twitter_follower",
  "Youtube Subscribers": "youtube_subscriber",
  // 'Linkedin Followers': 'linkedin_follower',
  // "Decided Business Type": "business_type",
  "City Presence": "city_presence",
  "Country Presence": "country_presence",

  "Description(Facebook)": "facebook_desc",
  "Description(Instragram)": "instragram_desc",
  "Description(Instagram)": "instragram_desc",
  "Description(LinkedIn)": "linkedin_desc",
  "Description(Youtube)": "youtube_desc",
  "Description(Twitter)": "twitter_desc",
  sector: "sector",
  "Business Type": "business_type",
};

const arrDataType = ["city_presence", "country_presence", "business_type"];

module.exports = {
  companyFieldMapping,
  companyContact,
  companyInfo,
  sector,
  tableColumnMap,
  arrDataType,
  biz_type,
};
