// module.exports = {

//     "Avertising  Network": "Advertising",
//     "ads txt": "Advertising",
//     "Ad Exchange": "Advertising",
//     "Audience Targeting": "Advertising",
//     "Facebook Exchange": "Advertising",
//     "Ad Server": "Advertising",
//     "Affiliate Programs": "Advertising",
//     "Contextual Advertising": "Advertising",
//     "Dynamic Creative Optimization": "Advertising",
//     "Digital Video Ads": "Advertising",
//     "Retargeting / Remarketing": "Advertising",
//     "Header Bidding": "Advertising",

//     "Application Performance": "Analytics and Tracking",
//     "A/B Testing": "Analytics and Tracking",
//     "Ad Analytics": "Analytics and Tracking",
//     "Conversion Optimization": "Analytics and Tracking",
//     "Advertiser Tracking": "Analytics and Tracking",
//     "Tag Management": "Analytics and Tracking",
//     "Audience Measurement": "Analytics and Tracking",
//     "Visitor Count Tracking": "Analytics and Tracking",

//     "Non Platform": "Ecommerce",
//     "Hosted Solution": "Ecommerce",
//     "Open Source": "Ecommerce",
//     // "Checkout Buttons": "Ecommerce",
//     // "Payment Acceptance": "Ecommerce",
//     // "Payments Processor": "Ecommerce",
//     // "Payment Currency": "Ecommerce",
//     "Payments Processor": "Payment",
//     "Payment Currency": "Payment",
//     "Checkout Buttons": "Payment",

//     "Live Chat": "Widget",
//     "Login": "Widget",
//     "Ticketing System": "Widget",
//     "Bookings": "Widget",
//     "Social Sharing": "Widget",
//     "Social Management": "Widget",

//     // "Cloud Hosting": "Hosting",
//     // "Cloud PaaS": "Hosting",
//     // "Dedicated Hosting": "Hosting",
//     // "Business Email Hosting": "Hosting",
//     // "Web Hosting Provider Email": "Hosting",
//     // "Marketing Platform": "Hosting",

//     "Cloud Hosting": "Web Hosting Providers",
//     "Cloud PaaS": "Web Hosting Providers",
//     "Dedicated Hosting": "Web Hosting Providers",
//     "Business Email Hosting": "Email Hosting Providers",
//     "Web Hosting Provider Email": "Email Hosting Providers",
//     "Marketing Platform": "Email Hosting Providers",

//     // "CRM": "Productivity",
//     // "Lead Generation": "Productivity",
//     // "Marketing Automation": "Productivity",
//     // "Product Recommendations": "Productivity",
//     // "Feedback Forms and Surveys": "Productivity",
//     // "Campaign Management": "Productivity"

//     "CRM": "Analytics and Tracking",
//     "Lead Generation": "Analytics and Tracking",
//     "Marketing Automation": "Widgets",
//     "Product Recommendations": "Analytics and Tracking",
//     "Feedback Forms and Surveys": "Analytics and Tracking",
//     "Campaign Management": "Email Hosting Providers"
// }

module.exports = {
    "Advertising": ["Avertising  Network",
        "ads txt",
        "Ad Exchange",
        "Audience Targeting",
        "Facebook Exchange",
        "Ad Server",
        "Affiliate Programs",
        "Contextual Advertising",
        "Dynamic Creative Optimization",
        "Digital Video Ads",
        "Retargeting / Remarketing",
        "Header Bidding"],
    "Analytics and Tracking": ["Application Performance",
        "A/B Testing",
        "Ad Analytics",
        "Conversion Optimization",
        "Advertiser Tracking",
        "Tag Management",
        "Audience Measurement",
        "Visitor Count Tracking",
        "CRM",
        "Lead Generation",
        "Product Recommendations",
        "Feedback Forms and Surveys"],
    "Ecommerce": ["Non Platform",
        "Hosted Solution",
        "Open Source"],
    "Payment": ["Checkout Buttons",
        "Payments Processor",
        "Payment Currency"],
    "Widgets": ["Live Chat",
        "Login",
        "Ticketing System",
        "Bookings",
        "Social Sharing",
        "Schedule Management",
        "Marketing Automation"],
    "Web Hosting Providers": ["Cloud Hosting",
        "Cloud PaaS",
        "Dedicated Hosting"],
    "Email Hosting Providers": ["Business Email Hosting",
        "Web Hosting Provider Email",
        "Marketing Platform",
        "Campaign Management"]
}

