module.exports = {
    "a/b testing": "Analytics and Tracking",
    "ad analytics": "Analytics and Tracking",
    "ad exchange": "Advertising",
    "ad server": "Advertising",
    "ads txt": "Advertising",
    "advertiser tracking": "Analytics and Tracking",
    "affiliate programs": "Advertising",
    "application performance": "Analytics and Tracking",
    "audience measurement": "Analytics and Tracking",
    "audience targeting": "Advertising",
    "avertising network": "Advertising",
    "bookings": "Widgets",
    "business email hosting": "Email Hosting Providers",
    "campaign management": "Email Hosting Providers",
    "checkout buttons": "Payment",
    "cloud hosting": "Web Hosting Providers",
    "cloud paas": "Web Hosting Providers",
    "contextual advertising": "Advertising",
    "conversion optimization": "Analytics and Tracking",
    "crm": "Analytics and Tracking",
    "dedicated hosting": "Web Hosting Providers",
    "digital video ads": "Advertising",
    "dynamic creative optimization": "Advertising",
    "facebook exchange": "Advertising",
    "feedback forms and surveys": "Analytics and Tracking",
    "header bidding": "Advertising",
    "hosted solution": "Ecommerce",
    "lead generation": "Analytics and Tracking",
    "live chat": "Widgets",
    "login": "Widgets",
    "marketing automation": "Widgets",
    "marketing platform": "Email Hosting Providers",
    "non platform": "Ecommerce",
    "open source": "Ecommerce",
    "payment acceptance": "Payment",
    "payment currency": "Payment",
    "payments processor": "Payment",
    "product recommendations": "Analytics and Tracking",
    "retargeting / remarketing": "Advertising",
    "schedule management": "Widgets",
    "social sharing": "Widgets",
    "tag management": "Analytics and Tracking",
    "ticketing system": "Widgets",
    "visitor count tracking": "Analytics and Tracking",
    "web hosting provider email": "Email Hosting Providers",
}