module.exports = {
    "Advertising": ["Avertising  Network",
        "ads txt",
        "Ad Exchange",
        "Audience Targeting",
        "Facebook Exchange",
        "Ad Server",
        "Affiliate Programs",
        "Contextual Advertising",
        "Dynamic Creative Optimization",
        "Digital Video Ads",
        "Retargeting / Remarketing",
        "Header Bidding"],
    "Analytics and Tracking": ["Application Performance",
        "A/B Testing",
        "Ad Analytics",
        "Conversion Optimization",
        "Advertiser Tracking",
        "Tag Management",
        "Audience Measurement",
        "Visitor Count Tracking",
        "CRM"],
    "Ecommerce": ["Non Platform",
        "Hosted Solution",
        "Open Source",
        "Checkout Buttons",
        "Payments Processor",
        "Payment Currency"],
    "Widgets": ["Live Chat",
        "Login",
        "Ticketing System",
        "Bookings",
        "Social Sharing",
        "Schedule Management",
    ],
    "Hosting": ["Cloud Hosting",
        "Cloud PaaS",
        "Dedicated Hosting",
        "Business Email Hosting",
        "Web Hosting Provider Email",
        "Marketing Platform"],
    "Productivity": [
        "CRM",
        "Campaign Management",
        "Lead Generation",
        "Product Recommendations",
        "Feedback Forms and Surveys",
        "Marketing Automation"]
}