module.exports = {
    "Google": ["google ad", "google ads", "google advertising", "google adword ", "google adwords", "gdn", "google display network", "google display ad", "google display ads", "google display advertising", "google seach ad ", "google search ads", "google search advertising", "sem", "search engine marketing", "search engine advertising", "youtube ad", "youtube ads", "youtube advertising", "search and keyword advertising", "search ad", "search ads", "search advertising", "google ad manager", "google ads manager", "google advertising manager", "google marketing platform", "google partner", "google premier partner", "google partners", "google search partner ", "google shopping", "google shopping ad", "google shopping ads", "google shopping advertising", "google ad remarking", "google ads remarketing", "google advertising remarketing", "google cpc", "google cpc ad ", "google cpc ads", "google cpc advertising", "google cost per click", "google cost per click ad", "google cost per click ads", "google cost per click advertising", "google discovery ad", "google discovery ads", "google discovery advertising", "google video ad", "google video ads", "google video advertising", "adword marketing", "adwords marketing", "google conversion tracking", "google tag manager", "google ad certification", "google ads certification", "google advertising certification", "trueview", "trueview instream", "trueview in stream", "trueview video discovery ad", "trueview video discovery ads", "trueview video discovery advertising", "google search network", "admob", "rlsa", "remarketing lists for search ads", "google merchant center", "google merchant centers", "universal app campaign"],
    "Social": ["social advertising",
        "social ads",
        "social ad",
        "social media advertising",
        "social media ads",
        "social media ad",
        "zalo advertising",
        "zalo ads",
        "zalo ad",
        "facebook advertising",
        "facebook ads",
        "facebook ad",
        "facebook app ads",
        "facebook app ad",
        "facebook app advertising",
        "facebook messenger advertising",
        "facebook messenger ads",
        "facebook messenger ad",
        "facebook autoad ",
        "facebook autoads",
        "facebook automated ads",
        "facebook automated advertising",
        "page like advertising",
        "page like ads",
        "page like ad",
        "instagram advertising",
        "instagram ads",
        "instagram ad",
        "twitter advertising",
        "twitter ads",
        "twitter ad",
        "tiktok advertising",
        "tiktok ads",
        "tiktok ad",
        "snapchat advertising",
        "snapchat ads",
        "snapshot ad",
        "pinterest advertising",
        "pinterest ads",
        "pinterest ad",
        "carousel advertising",
        "carousel ads",
        "carousel ad",
        "linkedin advertising",
        "linkedin ads",
        "linkedin ad",
        "social advertising campaign",
        "social ads campaign",
        "social ad campaign",
        "social media marketing",
        "social media marketing and management",
        "social media campaign",
        "facebook partner",
        "facebook marketing partners",
        "instagram marketing partner",
        "instagram marketing partners",
        "twitter marketing partner",
        "twitter marketing partners",
        "whatapps ad",
        "whatsapp ads",
        "whatsapp advertising",
        "line ad",
        "line ads",
        "line advertising",
        "facebook video ad",
        "facebook video ads",
        "facebook video advertising",
        "facebook shopping ad",
        "facebook shopping ads",
        "facebook shopping advertising",
        "facebook followers ad",
        "facebook followers ads",
        "facebook followers advertising",
        "instagram story ad",
        "instagram story ads",
        "instagram story advertising",
        "instagram video ad",
        "instagram video ads",
        "instagram video advertising",
        "instagram shopping ad",
        "instagram shopping ads",
        "instagram shopping advertising",
        "instagram followers ad",
        "instagram followers ads",
        "instagram followers advertising",
        "facebook and instagram ad",
        "facebook and instagram ads",
        "facebook and instagram advertising",
        "social media ad",
        "social network ads",
        "social network advertising",
        "facebook campaign",
        "instagram campaign",
        "facebook pixel",
        "facebook cpc",
        "facebook ads manager",
        "facebook advertising manager",
        "facebook business manager",
        "facebook blueprint",
        "audience network",
        "zalo",
        "twitter",
        "facebook",
        "social media strategy",
        "facebook marketing",
        "instagram marketing",
        "twitter marketing",
        "tiktok marketing",
        "snapshot marketing",
        "pinterest marketing",
        "carousel marketing",
        "linkedin marketing"]
}