module.exports = {
    "ads txt": "Advertising",
    "Audience Targeting": "Advertising",
    "Contextual Advertising": "Advertising",
    "Dynamic Creative Optimization": "Advertising",
    "Digital Video Ads": "Advertising",
    "Retargeting / Remarketing": "Advertising",
    "Application Performance": "Analystics",
    "Conversion Optimization": "Analystics",
    "Advertiser Tracking": "Analystics",
    "Tag Management": "Analystics",
    "Audience Measurement": "Analystics",
    "Visitor Count Tracking": "Analystics",
    "Non Platform": "Ecommerce",
    "Hosted Solution": "Ecommerce",
    "Open Source": "Ecommerce",
    "Checkout Buttons": "Ecommerce",
    "Payments Processor": "Ecommerce",
    "Payment Currency": "Ecommerce",
    "Live Chat": "Widgets",
    "Login": "Widgets",
    "Ticketing System": "Widgets",
    "Bookings": "Widgets",
    "Social Sharing": "Widgets",
    "Schedule Management": "Widgets",
    "Cloud Hosting": "Hosting",
    "Cloud PaaS": "Hosting",
    "Dedicated Hosting": "Hosting",
    "Business Email Hosting": "Hosting",
    "Web Hosting Provider Email": "Hosting",
    "Marketing Platform": "Hosting",
    "CRM": "Productivity",
    "Campaign Management": "Productivity",
    "Lead Generation": "Productivity",
    "Product Recommendations": "Productivity",
    "Feedback Forms and Surveys": "Productivity",
    "Marketing Automation": "Productivity"
}